import { useEffect, useState } from "react";
import { ArrowLeft, Crown, Medal, RefreshCw, Trophy } from "lucide-react";
import { useNavigate } from "react-router-dom";
import { useUser } from "@/context/UserContext";
import { supabase } from "@/integrations/supabase/client";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import AvatarRenderer from "@/components/avatar/AvatarRenderer";
export default function EarlyLeaderboardPage(){
 const nav=useNavigate();const {user}=useUser();const [rows,setRows]=useState<any[]>([]);const [loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const {data,error}=await(supabase as any).rpc("get_early_leaderboard",{p_scope:"grade",p_period:"all",p_category:"overall"});if(!error)setRows(data??[]);setLoading(false)};useEffect(()=>{void load()},[]);
 const me=user?.username||user?.name;const myIndex=rows.findIndex(r=>r.username===me);const podium=rows.slice(0,3);const rest=rows.slice(3);
 return <div className="min-h-screen bg-background px-4 pb-24"><header className="sticky top-0 z-20 -mx-4 border-b bg-background/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-4xl items-center gap-3"><button className="inline-flex h-10 w-10 items-center justify-center rounded-full hover:bg-muted" onClick={()=>nav("/")} aria-label="Back"><ArrowLeft/></button><div className="flex-1"><h1 className="font-display text-xl font-bold">Early Ranks</h1><p className="text-xs text-muted-foreground">A friendly place to celebrate learning</p></div><Button size="icon" variant="outline" onClick={()=>void load()} aria-label="Refresh ranks"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></Button></div></header>
 <main className="mx-auto max-w-4xl space-y-5 py-5"><section className="rounded-[2rem] bg-gradient-to-br from-warning/15 via-primary/10 to-accent/10 p-5 sm:p-7"><div className="flex items-center gap-3"><div className="rounded-2xl bg-background p-3 text-3xl">🏆</div><div><p className="text-xs font-bold uppercase tracking-wide text-primary">Learning leaderboard</p><h2 className="text-3xl font-display font-bold">Grow together ⭐</h2></div></div>{myIndex>=0&&<p className="mt-3 text-sm font-semibold">Your current place: <span className="text-primary">#{myIndex+1}</span></p>}</section>
 {loading?<div className="rounded-2xl border p-8 text-center text-muted-foreground">Loading ranks…</div>:!rows.length?<div className="rounded-2xl border p-8 text-center text-muted-foreground">Ranks will appear as learners start playing.</div>:<><div className="grid grid-cols-3 items-end gap-2 sm:gap-4">{[1,0,2].map(i=>{const r=podium[i];if(!r)return <div key={i}/>;return <div key={i} className={`rounded-[1.5rem] border bg-card p-3 text-center ${i===0?"-translate-y-2 border-warning/50":"border-border"}`}><div className="mx-auto mb-2 flex justify-center">{i===0?<Crown className="text-warning"/>:<Medal className="text-primary" />}</div><AvatarRenderer avatar={r.avatar} size="sm"/><p className="mt-2 truncate text-sm font-bold">{r.username}</p><Badge className="mt-1">{Number(r.score).toLocaleString()} XP</Badge><p className="mt-1 text-[10px] text-muted-foreground">Level {r.level}</p></div>})}</div>
 <div className="space-y-2">{rest.map((r,i)=>{const rank=i+4;const mine=r.username===me;return <div key={r.username+"-"+rank} className={`flex items-center gap-3 rounded-2xl border p-3 ${mine?"border-primary bg-primary/5":"bg-card"}`}><div className="w-8 text-center font-bold text-muted-foreground">#{rank}</div><AvatarRenderer avatar={r.avatar} size="sm"/><div className="min-w-0 flex-1"><p className="truncate font-semibold">{r.username}{mine&&<span className="ml-2 text-xs text-primary">You</span>}</p><p className="text-xs text-muted-foreground">Level {r.level}</p></div><p className="font-display font-bold">{Number(r.score).toLocaleString()} XP</p></div>})}</div></>}</main></div>;
}