import{useMemo,useState}from"react";
import{ArrowLeft,Gamepad2,Lightbulb,Sparkles}from"lucide-react";
import{useNavigate}from"react-router-dom";
import{useUser}from"@/context/UserContext";
import{useEarlyReward}from"@/hooks/useEarlyReward";
import{useEarlyProgress}from"@/hooks/useEarlyProgress";
import{Card,CardContent}from"@/components/ui/card";
import{Badge}from"@/components/ui/badge";
import{getGradeProfile,toEarlyGrade}from"@/features/early/engine/gradeProfile";
import{GAME_CATALOG,gradeGameRounds,type GameKind}from"@/features/early/games/gameEngine";

export default function EarlyGamesPage(){
 const nav=useNavigate(),{user}=useUser(),reward=useEarlyReward(),{rows}=useEarlyProgress();
 const grade=toEarlyGrade(user?.grade),profile=getGradeProfile(grade);
 const[game,setGame]=useState<GameKind|null>(null),[round,setRound]=useState(0),[score,setScore]=useState(0),[selected,setSelected]=useState<string|null>(null),[rounds,setRounds]=useState(()=>gradeGameRounds("number",grade));
 const progress=useMemo(()=>Object.fromEntries(rows.map(r=>[r.activity_id,r.completions])),[rows]);
 const start=(id:GameKind)=>{setGame(id);setRound(0);setScore(0);setSelected(null);setRounds(gradeGameRounds(id,grade,Math.max(5,profile.sessionLength-1)))};
 const current=rounds[round];
 const choose=async(v:string)=>{if(selected||!current)return;setSelected(v);const ok=v===current.answer;if(ok){setScore(x=>x+1);await reward("gameCorrect",{activityId:`early-game-${game}`,skill:current.skill,completed:round===rounds.length-1});}window.setTimeout(()=>{if(round>=rounds.length-1){setGame(null);setSelected(null)}else{setRound(x=>x+1);setSelected(null)}},700)};
 if(!game)return <div className="min-h-screen bg-background px-4 pb-24"><header className="sticky top-0 z-20 -mx-4 border-b border-border bg-background/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-4xl items-center gap-3"><button className="inline-flex h-10 w-10 items-center justify-center rounded-full hover:bg-muted" onClick={()=>nav("/")} aria-label="Back"><ArrowLeft/></button><div className="flex-1"><p className="font-display text-xl font-bold">Play & Learn</p><p className="text-xs text-muted-foreground">{profile.label} • games adapt to your learning level</p></div><Gamepad2 className="h-6 w-6 text-primary"/></div></header><main className="mx-auto max-w-4xl space-y-6 py-6"><section className="rounded-[2rem] bg-primary p-6 text-primary-foreground shadow-lg sm:p-8"><div className="flex items-center gap-3"><span className="text-5xl">🎮</span><div><p className="font-semibold opacity-90">Master Minds Play Lab</p><h1 className="text-3xl font-display font-bold">Your games grow with you</h1></div></div><p className="mt-3 max-w-2xl opacity-90">KG builds foundations. Grades 1–2 add reasoning and real-world skills. Grades 3–4 unlock multiplication, fractions, time and deeper logic.</p></section><div className="grid grid-cols-2 gap-3 sm:grid-cols-3">{GAME_CATALOG.filter(g=>grade>=g.minGrade).map(g=><button key={g.id} onClick={()=>start(g.id)} className="min-h-44 rounded-[1.75rem] border border-border bg-card p-4 text-left shadow-sm transition hover:-translate-y-1 active:scale-[.98]"><div className="flex h-14 w-14 items-center justify-center rounded-2xl bg-primary/10 text-3xl">{g.icon}</div><h2 className="mt-3 font-display text-lg font-bold">{g.title}</h2><p className="mt-1 text-sm text-muted-foreground">{g.description}</p><div className="mt-3 flex items-center gap-2"><Badge variant="secondary">Lv {Math.min(5,1+Math.floor((progress[`early-game-${g.id}`]||0)/2))}</Badge><span className="text-xs text-muted-foreground">{progress[`early-game-${g.id}`]||0} plays</span></div></button>)}</div><Card><CardContent className="flex gap-3 p-4"><Lightbulb className="mt-0.5 h-5 w-5 shrink-0 text-warning"/><p className="text-sm text-muted-foreground">Every round changes. Keep practising to unlock harder questions and new mechanics.</p></CardContent></Card></main></div>;
 return <div className="min-h-screen bg-background px-4 pb-32"><header className="sticky top-0 z-20 -mx-4 border-b border-border bg-background/95 px-4 py-3 backdrop-blur"><div className="mx-auto flex max-w-2xl items-center gap-3"><button className="inline-flex h-10 w-10 items-center justify-center rounded-full hover:bg-muted" onClick={()=>setGame(null)} aria-label="Back to games"><ArrowLeft/></button><div className="flex-1"><p className="font-display font-bold">{GAME_CATALOG.find(g=>g.id===game)?.title}</p><p className="text-xs text-muted-foreground">Round {round+1} of {rounds.length} • {profile.label}</p></div><Badge variant="secondary"><Sparkles className="mr-1 h-3.5 w-3.5"/>{score}</Badge></div></header><main className="mx-auto max-w-2xl space-y-5 py-6"><div className="h-2 overflow-hidden rounded-full bg-muted"><div className="h-full bg-primary transition-all" style={{width:`${(round/rounds.length)*100}%`}}/></div>{current&&<Card className="rounded-[2rem]"><CardContent className="space-y-5 p-5 sm:p-8"><div className="rounded-3xl bg-primary/10 p-6 text-center">{current.visual&&<div className="mb-3 text-4xl leading-relaxed">{current.visual}</div>}<p className="text-xs font-semibold uppercase tracking-wide text-primary">Mission</p><h1 className="mt-2 text-2xl font-display font-bold sm:text-3xl">{current.prompt}</h1></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{current.options.map((o,i)=>{const chosen=selected===o,correct=o===current.answer;return <button key={o} disabled={!!selected} onClick={()=>choose(o)} className={`min-h-20 rounded-3xl border-2 border-b-4 px-4 text-left text-lg font-bold transition active:translate-y-0.5 ${selected?(correct?"border-success bg-success/10":"opacity-50"):"border-border bg-card hover:border-primary/50"} ${chosen&&!correct?"border-warning bg-warning/10":""}`}>{String.fromCharCode(65+i)}. {o}</button>})}</div>{selected&&<div role="status" aria-live="polite" className={`rounded-3xl p-4 text-center font-semibold ${selected===current.answer?"bg-success/15 text-success":"bg-warning/15 text-foreground"}`}>{selected===current.answer?"🎉 Brilliant! You solved it.":`💡 Good try! ${current.explain}`}</div>}</CardContent></Card>}</main></div>;
}