import React,{useMemo,useState}from"react";
import{ArrowLeft,Check,Globe2,Lightbulb,Sparkles,Volume2}from"lucide-react";
import{useNavigate}from"react-router-dom";
import{useUser}from"@/context/UserContext";
import{useEarlyReward}from"@/hooks/useEarlyReward";
import{toEarlyGrade,getGradeProfile}from"@/features/early/engine/gradeProfile";
import{readExposure,recordExposure}from"@/features/early/engine/exposure";
import{Button}from"@/components/ui/button";
import{Card,CardContent}from"@/components/ui/card";
import{Badge}from"@/components/ui/badge";

type Fact={id:string;min:number;icon:string;title:string;body:string;question:string;options:string[];answer:string;subject:string};
const facts:Fact[]=[
{id:"earth",min:0,icon:"🌍",title:"Our Amazing Planet",body:"Earth has land, water, air and living things. Water covers more of its surface than land.",question:"What covers most of Earth's surface?",options:["Water","Sand","Snow","Grass"],answer:"Water",subject:"World"},
{id:"bees",min:0,icon:"🐝",title:"Bee Builders",body:"Bees move pollen from flower to flower. This helps many plants make seeds.",question:"What do bees move?",options:["Pollen","Rocks","Rain","Snow"],answer:"Pollen",subject:"Science"},
{id:"rainbow",min:1,icon:"🌈",title:"Rainbow Science",body:"Sunlight can split into different colours when it passes through water droplets.",question:"What two things help make a rainbow?",options:["Sunlight and water","Moonlight and sand","Snow and fire","Wind and rocks"],answer:"Sunlight and water",subject:"Science"},
{id:"space",min:1,icon:"🚀",title:"Space Explorer",body:"The Sun is a star. Earth travels around the Sun, and the Moon travels around Earth.",question:"What is the Sun?",options:["A star","A planet","A moon","A cloud"],answer:"A star",subject:"Science"},
{id:"octopus",min:1,icon:"🐙",title:"Ocean Wonder",body:"An octopus has eight arms and lives in the ocean. Its arms help it explore and catch food.",question:"How many arms does an octopus have?",options:["Eight","Six","Ten","Four"],answer:"Eight",subject:"Science"},
{id:"plants",min:2,icon:"🌱",title:"Tiny Seed, Big Plant",body:"Plants use sunlight, water and carbon dioxide to make food in their leaves.",question:"What provides energy for many plants?",options:["Sunlight","Plastic","Darkness","Candy"],answer:"Sunlight",subject:"Science"},
{id:"ethiopia",min:2,icon:"🇪🇹",title:"Ethiopia & the World",body:"Ethiopia is in the Horn of Africa. Addis Ababa is its capital city.",question:"Which continent is Ethiopia in?",options:["Africa","Asia","Europe","Australia"],answer:"Africa",subject:"World"},
{id:"nile",min:3,icon:"💧",title:"Blue Nile Journey",body:"The Blue Nile flows out of Lake Tana in Ethiopia before continuing its long journey.",question:"Where does the Blue Nile begin in Ethiopia?",options:["Lake Tana","Lake Abaya","Lake Chad","Lake Victoria"],answer:"Lake Tana",subject:"World"},
{id:"heart",min:3,icon:"🫀",title:"Your Amazing Heart",body:"Your heart is a strong muscle that pumps blood around your body.",question:"What does the heart do?",options:["Pumps blood","Stores food","Makes bones","Sees light"],answer:"Pumps blood",subject:"Science"},
{id:"magnet",min:4,icon:"🧲",title:"Magnet Magic",body:"Magnets attract some metals, including iron and many kinds of steel.",question:"Which object is attracted by a magnet?",options:["Iron nail","Wooden spoon","Paper cup","Plastic toy"],answer:"Iron nail",subject:"Science"},
];
const speak=(text:string)=>{if("speechSynthesis"in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate:.9;speechSynthesis.speak(u)}};
export default function EarlyDiscoverPage(){
 const nav=useNavigate(),{user}=useUser(),reward=useEarlyReward(),grade=toEarlyGrade(user?.grade),profile=getGradeProfile(grade);
 const pool=useMemo(()=>{const seen=readExposure(user?.id,"discover");return facts.filter(f=>grade>=f.min).sort((a,b)=>(seen[a.id]?.last??0)-(seen[b.id]?.last??0));},[grade,user?.id]);
 const [index,setIndex]=useState(0),[selected,setSelected]=useState(""),[result,setResult]=useState<boolean|null>(null);
 const f=pool[index%Math.max(pool.length,1)]??facts[0];
 const choose=async(v:string)=>{if(selected)return;setSelected(v);const ok=v===f.answer;setResult(ok);recordExposure(user?.id,"discover",f.id,ok);if(ok)await reward("discoverCorrect",{activityId:`discover-${f.id}`,skill:f.subject.toLowerCase()});speak(ok?"Excellent discovery!":"Good try! Let's learn it together.");};
 const next=()=>{setSelected("");setResult(null);setIndex(i=>i+1)};
 return <div className="min-h-screen bg-background pb-24"><header className="sticky top-0 z-20 border-b border-border bg-background/95 px-4 py-3"><div className="mx-auto flex max-w-3xl items-center gap-3"><Button variant="ghost" size="icon" onClick={()=>nav("/")}><ArrowLeft/></Button><div className="flex-1"><p className="font-display text-lg font-bold">Discover</p><p className="text-xs text-muted-foreground">{profile.label} • Learn → Ask → Answer → Grow</p></div><Badge variant="secondary"><Sparkles className="mr-1 h-3.5 w-3.5"/>{index+1}</Badge></div></header><main className="mx-auto max-w-3xl space-y-5 px-4 py-6"><section className="rounded-[2rem] bg-accent/15 p-6 sm:p-8"><div className="flex items-center gap-3"><div className="flex h-16 w-16 items-center justify-center rounded-3xl bg-background text-4xl">{f.icon}</div><div><p className="font-semibold text-accent">Discovery for {profile.label}</p><h1 className="text-2xl font-display font-bold">{f.title}</h1></div></div><p className="mt-5 text-lg leading-8">{f.body}</p><Button variant="outline" className="mt-4" onClick={()=>speak(f.body)}><Volume2 className="mr-2 h-4 w-4"/>Listen</Button></section><Card className="rounded-[2rem]"><CardContent className="p-5 sm:p-7"><div className="flex items-center gap-2"><Lightbulb className="h-5 w-5 text-warning"/><p className="font-display font-bold">Curiosity challenge</p></div><h2 className="mt-3 text-xl font-bold">{f.question}</h2><div className="mt-4 grid grid-cols-1 gap-3 sm:grid-cols-2">{f.options.map(o=><Button key={o} variant="outline" disabled={!!selected} onClick={()=>choose(o)} className={`min-h-16 rounded-2xl text-sm font-bold ${selected&&o===f.answer?"border-success bg-success/10 text-success":selected&&o===f.options.find(x=>x===selected)?"border-warning":""}`}>{selected&&o===f.answer?<Check className="mr-2 h-4 w-4"/>:null}{o}</Button>)}</div>{selected&&<div role="status" aria-live="polite" className={`mt-5 rounded-2xl p-4 text-center font-bold ${result?"bg-success/15 text-success":"bg-warning/15 text-foreground"}`}>{result?"🎉 Excellent! You unlocked a discovery reward.":`💡 Good try. The answer is ${f.answer}. Now you know something new!`}</div>}{selected&&<Button className="mt-4 min-h-12 w-full rounded-2xl" onClick={next}>Next discovery →</Button>}</CardContent></Card><div className="flex items-center justify-center gap-2 text-sm text-muted-foreground"><Globe2 className="h-4 w-4"/>Your discovery path adapts by grade and remembers what you have seen.</div></main></div>;
}