// This file is auto-generated by Lovable. Do not modify it.

import { supabase } from "../supabase/client";

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple", opts?: SignInOptions) => {
      const { data, error } = await supabase.auth.signInWithOAuth({
        provider,
        options: {
          redirectTo: opts?.redirect_uri,
          queryParams: opts?.extraParams,
        },
      });

      if (error) {
        return { error, redirected: false, tokens: undefined };
      }

      // Supabase OAuth generally redirects immediately when URL is returned.
      if (data?.url) {
        return { redirected: true, tokens: undefined };
      }

      return { redirected: false, tokens: undefined };
    },
  },
};
