
import React, { createContext, useContext, useState, ReactNode } from "react";

type Language = "english" | "amharic" | "afaan-oromoo";

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  english: {
    // General
    welcome: "Welcome to",
    "app-name": "MASTER MINDS",
    "app-tagline": "Where Learning Meets Adventure • Battle • Win",
    "smart-quiz-world": "A Smart Multiplayer Quiz World",
    "created-by": "Created by",
    start: "START",
    about: "About",
    "about-master-minds": "About Master Minds",
    "about-description": "Master Minds is a revolutionary educational platform combining the thrill of gaming with powerful learning tools.",
    "realtime-battles": "Real-time multiplayer quiz battles",
    "adaptive-difficulty": "Adaptive difficulty & XP progression",
    "tournaments-leaderboards": "Tournaments & global leaderboards",
    "multi-language": "English, Amharic & Afaan Oromoo",
    "inspired-by": "Inspired by PUBG, Duolingo & 99math",
    "choose-role": "Choose Your Role",
    "select-role-desc": "Select how you want to use Master Minds",
    "learn-play-win": "Learn. Play. Win.",
    loading: "Loading...",

    // Roles
    student: "Student",
    teacher: "Teacher",
    admin: "Administrator",
    manager: "Manager",
    "student-desc": "Learn, compete & earn rewards",
    "teacher-desc": "Create exams & monitor students",
    "admin-desc": "Full system control & management",
    "manager-desc": "Organization management",

    // Auth
    login: "Login",
    signup: "Sign Up",
    "student-signup": "Student Sign Up",
    "student-login": "Student Login",
    "teacher-signup": "Teacher Sign Up",
    "teacher-login": "Teacher Login",
    "admin-signup": "Admin Sign Up",
    "admin-login": "Admin Login",
    "manager-signup": "Manager Sign Up",
    "manager-login": "Manager Login",
    "full-name": "Full Name",
    "enter-full-name": "Enter your full name",
    email: "Email",
    "enter-email": "Enter your email (for recovery)",
    username: "Username",
    "choose-username": "Choose a username",
    "enter-username": "Enter your username",
    "username-for-login": "This will be used for login",
    password: "Password",
    "enter-password": "Enter your password",
    "min-6-chars": "Minimum 6 characters",
    "create-account": "Create Account",
    "or-continue-with": "Or continue with",
    "sign-in-google": "Sign in with Google",
    "already-have-account": "Already have an account? Login",
    "no-account": "Don't have an account? Sign up",
    "back-to-welcome": "Back to Welcome",
    "please-enter-name": "Please enter your full name",
    "please-enter-email": "Please enter your email",
    "please-enter-username": "Please enter a username",
    "username-no-spaces": "Username cannot contain spaces",
    "please-enter-password": "Please enter your password",
    "password-min-length": "Password must be at least 6 characters",
    "auth-failed": "Authentication failed. Please try again.",
    "google-signin-failed": "Google sign in failed",
    "signed-in-google": "Signed in with Google!",

    // Profile Setup
    "complete-profile": "Complete Your Profile",
    "setup-student-profile": "Let's set up your student profile",
    gender: "Gender",
    "select-gender": "Select your gender",
    male: "Male",
    female: "Female",
    other: "Other",
    grade: "Grade",
    "select-grade": "Select your grade",
    "education-level": "Education Level",
    "select-education": "Select your education level",
    elementary: "Elementary School",
    middle: "Middle School",
    high: "High School",
    university: "University",
    next: "Next",
    back: "Back",
    "create-avatar": "Create Your Avatar",
    "choose-avatar-desc": "Choose an avatar that represents you",
    "complete-setup": "Complete Setup",

    // Navigation & Menu
    settings: "Settings",
    profile: "Profile",
    language: "Language",
    quiz: "Quiz",
    multiplayer: "Multiplayer",
    leaderboard: "Leaderboard",
    friends: "Friends",
    logout: "Logout",
    save: "Save",
    cancel: "Cancel",
    "quick-play": "Quick Play",
    "1v1-battle": "1v1 Battle",
    "join-lobby": "Join Lobby",
    "game-lobby": "Game Lobby",
    "avatar-store": "Avatar Store",
    tournaments: "Tournaments",
    mathematics: "Mathematics",
    science: "Science",
    english: "English",
    "general-knowledge": "General Knowledge",
    "ai-tutor": "AI Tutor",
    "learning-dna": "Learning DNA",
    "social-feed": "Social Feed",
    "academic-mode": "Academic Mode",

    // Categories
    all: "All",
    play: "Play",
    learn: "Learn",
    compete: "Compete",
    social: "Social",

    // Descriptions
    "jump-into-quiz": "Jump into a random quiz",
    "challenge-player": "Challenge a player",
    "find-matches": "Find matches",
    "test-knowledge": "Test your knowledge",
    "compete-friends": "Compete with friends",
    "join-matches-chat": "Join matches & chat",
    "see-whos-top": "See who's on top",
    "customize-look": "Customize your look",
    "global-competitions": "Global competitions",
    "numbers-algebra": "Numbers & algebra",
    "physics-chemistry": "Physics & chemistry",
    "grammar-vocabulary": "Grammar & vocabulary",
    "history-geography": "History & geography",
    "24-7-ai-helper": "24/7 AI helper",
    "your-brain-map": "Your brain map",
    "connect-chat": "Connect & chat",
    "posts-updates": "Posts & updates",
    preferences: "Preferences",

    // Settings
    "customize-experience": "Customize your experience",
    "avatar-editor": "Avatar Editor",
    general: "General",
    sound: "Sound",
    alerts: "Alerts",
    privacy: "Privacy",
    "choose-language": "Choose your preferred language",
    active: "Active",
    "sound-settings": "Sound Settings",
    "adjust-audio": "Adjust audio preferences",
    "master-volume": "Master Volume",
    mute: "Mute",
    max: "Max",
    "sound-effects": "Sound Effects",
    "ui-sounds": "UI sounds and game effects",
    vibration: "Vibration",
    "haptic-feedback": "Haptic feedback on actions",
    notifications: "Notifications",
    "manage-alerts": "Manage your alerts",
    "enable-all-notifications": "Enable All Notifications",
    "master-switch": "Master switch for all alerts",
    "friend-requests": "Friend Requests",
    "when-someone-adds": "When someone adds you",
    messages: "Messages",
    "new-chat-messages": "New chat messages",
    "game-invites": "Game Invites",
    "multiplayer-invitations": "Multiplayer invitations",
    "daily-quiz-reminder": "Daily Quiz Reminder",
    "daily-challenge-notif": "Daily challenge notifications",
    achievements: "Achievements",
    "when-unlock-badges": "When you unlock badges",
    "privacy-security": "Privacy & Security",
    "manage-privacy": "Manage your privacy",
    "public-profile": "Public Profile",
    "others-see-stats": "Others can see your stats",
    "show-online-status": "Show Online Status",
    "friends-see-online": "Let friends see when you're online",
    "activity-history": "Activity History",
    "track-progress": "Track your learning progress",
    "account-actions": "Account Actions",
    "log-out": "Log Out",
    "delete-account": "Delete Account",
    "logged-out": "Logged out successfully",

    // Enhanced Settings
    "profile-settings": "Profile Settings",
    "display-name": "Display Name",
    "your-display-name": "Your display name",
    "email-address": "Email Address",
    "grade-level": "Grade Level",
    "account-type": "Account Type",
    "bio-optional": "Bio (Optional)",
    "tell-about-yourself": "Tell others about yourself...",
    "quick-actions": "Quick Actions",
    "save-profile": "Save Profile",
    "export-data": "Export Data",
    "push-notifications": "Push Notifications",
    "receive-quiz-reminders": "Receive quiz reminders and updates",
    "play-sounds": "Play sounds during quizzes",
    "mindforge-reactions": "MindForge Reactions™",
    "show-cinematic": "Show cinematic answer reactions",
    "reduced-motion": "Reduced Motion Mode",
    "limit-movement": "Limit movement-heavy effects for accessibility",
    "autosave-progress": "Auto-save Progress",
    "auto-save-quiz": "Automatically save quiz progress",
    "default-difficulty": "Default Difficulty",
    easy: "Easy",
    medium: "Medium",
    hard: "Hard",
    "privacy-display": "Privacy & Display",
    "show-avatar": "Show Avatar",
    "display-avatar-others": "Display your avatar to others",
    "show-rank": "Show Rank",
    "display-rank-profile": "Display your rank on profile",
    "allow-friend-requests": "Allow Friend Requests",
    "let-others-add": "Let others send you friend requests",
    "saving-avatar": "Saving avatar...",
    "profile-saved": "Profile saved successfully!",
    "avatar-saved": "Avatar saved successfully!",
    "failed-save-profile": "Failed to save profile",
    "failed-save-avatar": "Failed to save avatar",
    "data-exported": "Data exported successfully!",
    "failed-export": "Failed to export data",
    "language-changed": "Language changed to",
    "account-deletion-confirm": "Account deletion requires confirmation. Contact support for assistance.",

    // Quiz
    "daily-challenge": "Daily Challenge",
    "level-up": "Level up!",
    "correct-answer": "Correct!",
    "wrong-answer": "Wrong answer",
    "try-again": "Try again",
    "quiz-completed": "Quiz completed",
    "start-quiz": "Start Quiz",
    difficulty: "Difficulty",
    questions: "Questions",
    "browse-quizzes": "Browse Quizzes",
    "quick-start": "Quick Start",
    "select-subject": "Select Subject",
    "select-difficulty": "Select Difficulty",
    "num-questions": "Number of Questions",
    "generate-quiz": "Generate Quiz",
    "no-quizzes": "No quizzes available",
    "correct-xp": "Correct! +15 XP awarded!",
    "incorrect-tomorrow": "Incorrect answer. Try again tomorrow!",
    "question-of": "Question {current} of {total}",
    score: "Score",
    "time-left": "Time Left",

    // Leaderboard
    "top-players": "Top Players",
    "this-week": "This Week",
    "this-month": "This Month",
    "all-time": "All Time",
    "your-rank": "Your Rank",
    "active-players": "Active Players",
    rank: "Rank",
    player: "Player",
    level: "Level",
    xp: "XP",

    // Social
    "social-hub": "Social Hub",
    "connect-community": "Connect with your community",
    feed: "Feed",
    groups: "Groups",

    // Multiplayer
    "create-room": "Create Room",
    "join-room": "Join Room",
    "room-name": "Room Name",
    "max-players": "Max Players",
    "waiting-players": "Waiting for players...",
    "game-starting": "Game starting...",
    ready: "Ready",
    "not-ready": "Not Ready",

    // Common
    "get-started": "Get Started",
    "tap-to-continue": "Tap anywhere to continue",
    theme: "Theme",
    "dark-mode": "Dark Mode",
    "light-mode": "Light Mode",
    music: "Music",
    help: "Help & Support",
    terms: "Terms & Conditions",
    "privacy-policy": "Privacy Policy",
    version: "Version",
    "teacher-dashboard": "Teacher Dashboard",
    "admin-dashboard": "Admin Dashboard",
    "create-quiz": "Create Quiz",
    "my-quizzes": "My Quizzes",
    "student-progress": "Student Progress",
    analytics: "Analytics",
    resources: "Learning Resources",
    assignments: "Assignments",
    "flashcards": "Flashcards",
    "topic-coverage": "Topic Coverage",
    "exam-mode": "Exam Mode",
    "study-planner": "Study Planner",
    "academic-insights": "Academic Insights",

    // Footer
    "app-version": "Master Minds v1.0",
    "contact": "Contact",
  },
  amharic: {
    // General
    welcome: "ወደ ማስተር ማይንድስ እንኳን ደህና መጡ",
    "app-name": "ማስተር ማይንድስ",
    "app-tagline": "ትምህርት ከጀብዱ ጋር የሚገናኝበት • ውድድር • ድል",
    "smart-quiz-world": "ብልጥ የብዙ ተጫዋች ጥያቄዎች ዓለም",
    "created-by": "የተሰራው በ",
    start: "ጀምር",
    about: "ስለ እኛ",
    "about-master-minds": "ስለ ማስተር ማይንድስ",
    "about-description": "ማስተር ማይንድስ የጨዋታ ደስታን ከትምህርት መሳሪያዎች ጋር የሚያጣምር አብዮታዊ የትምህርት መድረክ ነው።",
    "realtime-battles": "በቅጽበት የሚደረግ የጥያቄ ውድድር",
    "adaptive-difficulty": "ተለዋዋጭ ችግር ደረጃ እና XP ዕድገት",
    "tournaments-leaderboards": "ውድድሮች እና ዓለም አቀፍ ደረጃዎች",
    "multi-language": "እንግሊዘኛ፣ አማርኛ እና አፋን ኦሮሞ",
    "inspired-by": "ተመስጦ ከ PUBG፣ Duolingo እና 99math",
    "choose-role": "ሚናዎን ይምረጡ",
    "select-role-desc": "ማስተር ማይንድስን እንዴት መጠቀም እንደሚፈልጉ ይምረጡ",
    "learn-play-win": "ተማር። ተጫወት። አሸንፍ።",
    loading: "በመጫን ላይ...",

    // Roles
    student: "ተማሪ",
    teacher: "መምህር",
    admin: "አስተዳዳሪ",
    manager: "ሥራ አስኪያጅ",
    "student-desc": "ተማር፣ ተወዳደር እና ሽልማት አግኝ",
    "teacher-desc": "ፈተናዎችን ፍጠር እና ተማሪዎችን ተቆጣጠር",
    "admin-desc": "ሙሉ ስርዓት ቁጥጥር እና አስተዳደር",
    "manager-desc": "ድርጅታዊ አስተዳደር",

    // Auth
    login: "ግባ",
    signup: "ተመዝገብ",
    "student-signup": "የተማሪ ምዝገባ",
    "student-login": "የተማሪ መግቢያ",
    "teacher-signup": "የመምህር ምዝገባ",
    "teacher-login": "የመምህር መግቢያ",
    "admin-signup": "የአስተዳዳሪ ምዝገባ",
    "admin-login": "የአስተዳዳሪ መግቢያ",
    "manager-signup": "የሥራ አስኪያጅ ምዝገባ",
    "manager-login": "የሥራ አስኪያጅ መግቢያ",
    "full-name": "ሙሉ ስም",
    "enter-full-name": "ሙሉ ስምዎን ያስገቡ",
    email: "ኢሜይል",
    "enter-email": "ኢሜይልዎን ያስገቡ (ለመልሶ ማግኛ)",
    username: "የተጠቃሚ ስም",
    "choose-username": "የተጠቃሚ ስም ይምረጡ",
    "enter-username": "የተጠቃሚ ስምዎን ያስገቡ",
    "username-for-login": "ይህ ለመግቢያ ይጠቀማል",
    password: "የይለፍ ቃል",
    "enter-password": "የይለፍ ቃልዎን ያስገቡ",
    "min-6-chars": "ቢያንስ 6 ቁምፊዎች",
    "create-account": "መለያ ፍጠር",
    "or-continue-with": "ወይም ይቀጥሉ በ",
    "sign-in-google": "በ Google ይግቡ",
    "already-have-account": "መለያ አለዎት? ይግቡ",
    "no-account": "መለያ የለዎትም? ይመዝገቡ",
    "back-to-welcome": "ወደ መግቢያ ተመለስ",
    "please-enter-name": "እባክዎ ሙሉ ስምዎን ያስገቡ",
    "please-enter-email": "እባክዎ ኢሜይልዎን ያስገቡ",
    "please-enter-username": "እባክዎ የተጠቃሚ ስም ያስገቡ",
    "username-no-spaces": "የተጠቃሚ ስም ባዶ ቦታ ሊኖረው አይችልም",
    "please-enter-password": "እባክዎ የይለፍ ቃል ያስገቡ",
    "password-min-length": "የይለፍ ቃል ቢያንስ 6 ቁምፊዎች መሆን አለበት",
    "auth-failed": "ማረጋገጫ አልተሳካም። እባክዎ እንደገና ይሞክሩ።",
    "google-signin-failed": "የ Google መግቢያ አልተሳካም",
    "signed-in-google": "በ Google ተገብቷል!",

    // Profile Setup
    "complete-profile": "መገለጫዎን ያጠናቅቁ",
    "setup-student-profile": "የተማሪ መገለጫዎን ያዘጋጁ",
    gender: "ፆታ",
    "select-gender": "ፆታዎን ይምረጡ",
    male: "ወንድ",
    female: "ሴት",
    other: "ሌላ",
    grade: "ክፍል",
    "select-grade": "ክፍልዎን ይምረጡ",
    "education-level": "የትምህርት ደረጃ",
    "select-education": "የትምህርት ደረጃዎን ይምረጡ",
    elementary: "የመጀመሪያ ደረጃ ትምህርት ቤት",
    middle: "መካከለኛ ደረጃ ትምህርት ቤት",
    high: "ሁለተኛ ደረጃ ትምህርት ቤት",
    university: "ዩኒቨርሲቲ",
    next: "ቀጣይ",
    back: "ተመለስ",
    "create-avatar": "አቫታርዎን ይፍጠሩ",
    "choose-avatar-desc": "የሚወክልዎ አቫታር ይምረጡ",
    "complete-setup": "ማዋቀሩን ያጠናቅቁ",

    // Navigation & Menu
    settings: "ቅንብሮች",
    profile: "መገለጫ",
    language: "ቋንቋ",
    quiz: "ጥያቄዎች",
    multiplayer: "በጋራ ጨዋታ",
    leaderboard: "የዕድገት ደረጃ",
    friends: "ጓደኞች",
    logout: "ውጣ",
    save: "አስቀምጥ",
    cancel: "ይቅር",
    "quick-play": "ፈጣን ጨዋታ",
    "1v1-battle": "1 ለ 1 ውድድር",
    "join-lobby": "ሎቢ ግባ",
    "game-lobby": "የጨዋታ ሎቢ",
    "avatar-store": "የአቫታር ሱቅ",
    tournaments: "ውድድሮች",
    mathematics: "ሒሳብ",
    science: "ሳይንስ",
    english: "እንግሊዘኛ",
    "general-knowledge": "አጠቃላይ ዕውቀት",
    "ai-tutor": "AI አስተማሪ",
    "learning-dna": "የመማር ዲኤንኤ",
    "social-feed": "ማህበራዊ ፊድ",
    "academic-mode": "የትምህርት ሁነታ",

    // Categories
    all: "ሁሉም",
    play: "ተጫወት",
    learn: "ተማር",
    compete: "ተወዳደር",
    social: "ማህበራዊ",

    // Descriptions
    "jump-into-quiz": "ወደ የዘፈቀደ ጥያቄ ዝለል",
    "challenge-player": "ተጫዋች ፈታተን",
    "find-matches": "ጨዋታዎችን ፈልግ",
    "test-knowledge": "ዕውቀትህን ፈትን",
    "compete-friends": "ከጓደኞች ጋር ተወዳደር",
    "join-matches-chat": "ጨዋታዎችን ተቀላቀል እና ተወያይ",
    "see-whos-top": "ማን ቀዳሚ እንደሆነ ተመልከት",
    "customize-look": "መልክዎን ያሳምሩ",
    "global-competitions": "ዓለም አቀፍ ውድድሮች",
    "numbers-algebra": "ቁጥሮች እና አልጀብራ",
    "physics-chemistry": "ፊዚክስ እና ኬሚስትሪ",
    "grammar-vocabulary": "ሰዋስው እና ቃላት",
    "history-geography": "ታሪክ እና ጂኦግራፊ",
    "24-7-ai-helper": "24/7 AI ረዳት",
    "your-brain-map": "የአንጎል ካርታዎ",
    "connect-chat": "ተገናኝ እና ተወያይ",
    "posts-updates": "ልጥፎች እና ዝማኔዎች",
    preferences: "ምርጫዎች",

    // Settings
    "customize-experience": "ተሞክሮዎን ያበጁ",
    "avatar-editor": "የአቫታር አርታኢ",
    general: "አጠቃላይ",
    sound: "ድምፅ",
    alerts: "ማንቂያዎች",
    privacy: "ግላዊነት",
    "choose-language": "የሚመርጡትን ቋንቋ ይምረጡ",
    active: "ንቁ",
    "sound-settings": "የድምፅ ቅንብሮች",
    "adjust-audio": "የድምፅ ምርጫዎችን ያስተካክሉ",
    "master-volume": "ዋና ድምፅ",
    mute: "ዝም",
    max: "ከፍተኛ",
    "sound-effects": "ድምፃዊ ተፅዕኖዎች",
    "ui-sounds": "የUI ድምፆች እና የጨዋታ ተፅዕኖዎች",
    vibration: "ማንቀጥቀጥ",
    "haptic-feedback": "በድርጊቶች ላይ ንዝረት",
    notifications: "ማሳወቂያዎች",
    "manage-alerts": "ማንቂያዎችዎን ያስተዳድሩ",
    "enable-all-notifications": "ሁሉንም ማሳወቂያዎች አንቃ",
    "master-switch": "ለሁሉም ማንቂያዎች ዋና ማብሪያ",
    "friend-requests": "የጓደኝነት ጥያቄዎች",
    "when-someone-adds": "አንድ ሰው ሲጨምርዎት",
    messages: "መልዕክቶች",
    "new-chat-messages": "አዲስ የውይይት መልዕክቶች",
    "game-invites": "የጨዋታ ግብዣዎች",
    "multiplayer-invitations": "የብዙ ተጫዋች ግብዣዎች",
    "daily-quiz-reminder": "ዕለታዊ ጥያቄ ማስታወሻ",
    "daily-challenge-notif": "ዕለታዊ ፈተና ማሳወቂያዎች",
    achievements: "ስኬቶች",
    "when-unlock-badges": "ባጆች ሲከፍቱ",
    "privacy-security": "ግላዊነት እና ደህንነት",
    "manage-privacy": "ግላዊነትዎን ያስተዳድሩ",
    "public-profile": "ይፋዊ መገለጫ",
    "others-see-stats": "ሌሎች ስታቲስቲክስዎን ማየት ይችላሉ",
    "show-online-status": "የመስመር ላይ ሁኔታ አሳይ",
    "friends-see-online": "ጓደኞችዎ መስመር ላይ መሆንዎን ያዩ",
    "activity-history": "የእንቅስቃሴ ታሪክ",
    "track-progress": "የመማር እድገትዎን ይከታተሉ",
    "account-actions": "የመለያ ድርጊቶች",
    "log-out": "ውጣ",
    "delete-account": "መለያ ሰርዝ",
    "logged-out": "በተሳካ ሁኔታ ወጥቷል",

    // Enhanced Settings
    "profile-settings": "የመገለጫ ቅንብሮች",
    "display-name": "የማሳያ ስም",
    "your-display-name": "የማሳያ ስምዎ",
    "email-address": "ኢሜይል አድራሻ",
    "grade-level": "የክፍል ደረጃ",
    "account-type": "የመለያ ዓይነት",
    "bio-optional": "ስለ ራስ (አማራጭ)",
    "tell-about-yourself": "ስለራስዎ ይንገሩ...",
    "quick-actions": "ፈጣን ድርጊቶች",
    "save-profile": "መገለጫ አስቀምጥ",
    "export-data": "ውሂብ ላክ",
    "push-notifications": "ማሳወቂያዎች",
    "receive-quiz-reminders": "የጥያቄ ማስታወሻዎችን እና ዝማኔዎችን ይቀበሉ",
    "play-sounds": "በጥያቄዎች ወቅት ድምፆችን ያጫውቱ",
    "mindforge-reactions": "MindForge Reactions™",
    "show-cinematic": "ሲኒማቲክ የመልስ ምላሾችን አሳይ",
    "reduced-motion": "ቀነሰ እንቅስቃሴ ሁነታ",
    "limit-movement": "ለተደራሽነት ከባድ እንቅስቃሴ ተፅዕኖዎችን ይገድቡ",
    "autosave-progress": "ራስ-ሰርተው ያስቀምጡ",
    "auto-save-quiz": "የጥያቄ እድገትን በራስ ሰር ያስቀምጡ",
    "default-difficulty": "ነባሪ ችግር ደረጃ",
    easy: "ቀላል",
    medium: "መካከለኛ",
    hard: "ከባድ",
    "privacy-display": "ግላዊነት እና ማሳያ",
    "show-avatar": "አቫታር አሳይ",
    "display-avatar-others": "አቫታርዎን ለሌሎች ያሳዩ",
    "show-rank": "ደረጃ አሳይ",
    "display-rank-profile": "ደረጃዎን በመገለጫ ላይ ያሳዩ",
    "allow-friend-requests": "የጓደኝነት ጥያቄዎችን ፍቀድ",
    "let-others-add": "ሌሎች የጓደኝነት ጥያቄ እንዲልኩልዎ ያድርጉ",
    "saving-avatar": "አቫታር በማስቀመጥ ላይ...",
    "profile-saved": "መገለጫ በተሳካ ሁኔታ ተቀምጧል!",
    "avatar-saved": "አቫታር በተሳካ ሁኔታ ተቀምጧል!",
    "failed-save-profile": "መገለጫ ማስቀመጥ አልተሳካም",
    "failed-save-avatar": "አቫታር ማስቀመጥ አልተሳካም",
    "data-exported": "ውሂብ በተሳካ ሁኔታ ተልኳል!",
    "failed-export": "ውሂብ መላክ አልተሳካም",
    "language-changed": "ቋንቋ ተቀይሯል ወደ",
    "account-deletion-confirm": "መለያ ለመሰረዝ ማረጋገጫ ያስፈልጋል። ለእገዛ ድጋፍን ያግኙ።",

    // Quiz
    "daily-challenge": "የዕለት ፈተና",
    "level-up": "ደረጃ ዕድገት!",
    "correct-answer": "ትክክል!",
    "wrong-answer": "የተሳሳተ መልስ",
    "try-again": "እንደገና ሞክር",
    "quiz-completed": "ጥያቄዎች ተጠናቀቁ",
    "start-quiz": "ጥያቄ ጀምር",
    difficulty: "ችግር ደረጃ",
    questions: "ጥያቄዎች",
    "browse-quizzes": "ጥያቄዎችን ይመልከቱ",
    "quick-start": "ፈጣን ጅምር",
    "select-subject": "ትምህርት ይምረጡ",
    "select-difficulty": "ችግር ደረጃ ይምረጡ",
    "num-questions": "የጥያቄዎች ብዛት",
    "generate-quiz": "ጥያቄ ፍጠር",
    "no-quizzes": "ጥያቄዎች አልተገኙም",
    "correct-xp": "ትክክል! +15 XP ተሸልሟል!",
    "incorrect-tomorrow": "የተሳሳተ መልስ። ነገ እንደገና ሞክር!",
    "question-of": "ጥያቄ {current} ከ {total}",
    score: "ነጥብ",
    "time-left": "የቀረ ጊዜ",

    // Leaderboard
    "top-players": "ምርጥ ተጫዋቾች",
    "this-week": "በዚህ ሳምንት",
    "this-month": "በዚህ ወር",
    "all-time": "ሁልጊዜ",
    "your-rank": "የእርስዎ ደረጃ",
    "active-players": "ንቁ ተጫዋቾች",
    rank: "ደረጃ",
    player: "ተጫዋች",
    level: "ደረጃ",
    xp: "XP",

    // Social
    "social-hub": "ማህበራዊ ማዕከል",
    "connect-community": "ከማህበረሰብዎ ጋር ይገናኙ",
    feed: "ፊድ",
    groups: "ቡድኖች",

    // Multiplayer
    "create-room": "ክፍል ፍጠር",
    "join-room": "ክፍል ተቀላቀል",
    "room-name": "የክፍል ስም",
    "max-players": "ከፍተኛ ተጫዋቾች",
    "waiting-players": "ተጫዋቾችን በመጠበቅ ላይ...",
    "game-starting": "ጨዋታ ይጀምራል...",
    ready: "ዝግጁ",
    "not-ready": "ዝግጁ አይደለም",

    // Common
    "get-started": "ይጀምሩ",
    "tap-to-continue": "ለመቀጠል የትኛውም ቦታ ይንኩ",
    theme: "ገጽታ",
    "dark-mode": "ጨለማ ሁነታ",
    "light-mode": "ብርሃን ሁነታ",
    music: "ሙዚቃ",
    help: "እገዛ እና ድጋፍ",
    terms: "የአገልግሎት ውል",
    "privacy-policy": "የግላዊነት ፖሊሲ",
    version: "ስሪት",
    "teacher-dashboard": "የመምህር ዳሽቦርድ",
    "admin-dashboard": "የአስተዳዳሪ ዳሽቦርድ",
    "create-quiz": "ጥያቄዎችን ፍጠር",
    "my-quizzes": "የእኔ ጥያቄዎች",
    "student-progress": "የተማሪ እድገት",
    analytics: "ትንታኔዎች",
    resources: "የመማሪያ ግብአቶች",
    assignments: "የቤት ስራዎች",
    "flashcards": "ፍላሽ ካርዶች",
    "topic-coverage": "የርዕስ ሽፋን",
    "exam-mode": "የፈተና ሁነታ",
    "study-planner": "የጥናት አቀናባሪ",
    "academic-insights": "የትምህርት ግንዛቤዎች",

    // Footer
    "app-version": "ማስተር ማይንድስ v1.0",
    "contact": "ያግኙን",
  },
  "afaan-oromoo": {
    // General
    welcome: "Master Minds tti baga nagaan dhuftan",
    "app-name": "MASTER MINDS",
    "app-tagline": "Bakka Barnoonni Adveencharii Waliin Wal Arguu • Dorgommii • Injifannoo",
    "smart-quiz-world": "Addunyaa Gaaffilee Taphataa Baay'ee Cimaa",
    "created-by": "Kan uumame",
    start: "JALQABI",
    about: "Waa'ee keenyaa",
    "about-master-minds": "Waa'ee Master Minds",
    "about-description": "Master Minds platfoormii barnootaa gamaaggamaa kan gammachuu taphaa meeshaalee barnootaa ciimaa waliin walitti fiduudha.",
    "realtime-battles": "Dorgommii gaaffilee yeroo qabatamaa",
    "adaptive-difficulty": "Sadarkaa rakkina jijjiiramaa fi guddina XP",
    "tournaments-leaderboards": "Dorgommiilee fi sadarkaa addunyaa",
    "multi-language": "Afaan Ingilizii, Amaaraa fi Afaan Oromoo",
    "inspired-by": "Kan kakaafame PUBG, Duolingo fi 99math irraa",
    "choose-role": "Gahee Kee Filadhu",
    "select-role-desc": "Master Minds akkamitti fayyadamuu akka barbaaddu filadhu",
    "learn-play-win": "Baradi. Taphadi. Injifadhu.",
    loading: "Fe'amaa jira...",

    // Roles
    student: "Barataa",
    teacher: "Barsiisaa",
    admin: "Bulchaa",
    manager: "Hooganaa",
    "student-desc": "Baradi, dorgomi fi badhaasa argi",
    "teacher-desc": "Qormaata uumi fi barattoota too'adhu",
    "admin-desc": "To'annoo sirna guutuu fi bulchiinsa",
    "manager-desc": "Bulchiinsa dhaabbataa",

    // Auth
    login: "Seeni",
    signup: "Galmaa'i",
    "student-signup": "Galmee Barataa",
    "student-login": "Seensa Barataa",
    "teacher-signup": "Galmee Barsiisaa",
    "teacher-login": "Seensa Barsiisaa",
    "admin-signup": "Galmee Bulchaa",
    "admin-login": "Seensa Bulchaa",
    "manager-signup": "Galmee Hooganaa",
    "manager-login": "Seensa Hooganaa",
    "full-name": "Maqaa Guutuu",
    "enter-full-name": "Maqaa guutuu kee galchi",
    email: "Imeelii",
    "enter-email": "Imeelii kee galchi (deebisiidhaan argachuuf)",
    username: "Maqaa Fayyadamaa",
    "choose-username": "Maqaa fayyadamaa filadhu",
    "enter-username": "Maqaa fayyadamaa kee galchi",
    "username-for-login": "Kun seensuuf kan itti fayyadamamu",
    password: "Jecha Darbii",
    "enter-password": "Jecha darbii kee galchi",
    "min-6-chars": "Xiqqaate qubee 6",
    "create-account": "Herrega Uumi",
    "or-continue-with": "Ykn itti fufi",
    "sign-in-google": "Google dhaan seeni",
    "already-have-account": "Herrega qabdaa? Seeni",
    "no-account": "Herrega hin qabduu? Galmaa'i",
    "back-to-welcome": "Gara baga nagaan dhuftee deebi'i",
    "please-enter-name": "Maaloo maqaa guutuu kee galchi",
    "please-enter-email": "Maaloo imeelii kee galchi",
    "please-enter-username": "Maaloo maqaa fayyadamaa galchi",
    "username-no-spaces": "Maqaan fayyadamaa bakka duwwaa qabaachuu hin danda'u",
    "please-enter-password": "Maaloo jecha darbii kee galchi",
    "password-min-length": "Jechi darbii xiqqaate qubee 6 ta'uu qaba",
    "auth-failed": "Mirkaneessuun hin milkoofne. Maaloo irra deebi'ii yaali.",
    "google-signin-failed": "Seensi Google hin milkoofne",
    "signed-in-google": "Google dhaan seename!",

    // Profile Setup
    "complete-profile": "Piroofaayilii Kee Xumuri",
    "setup-student-profile": "Piroofaayilii barataa kee qopheessuu",
    gender: "Saala",
    "select-gender": "Saala kee filadhu",
    male: "Dhiira",
    female: "Dhalaa",
    other: "Kan biraa",
    grade: "Kutaa",
    "select-grade": "Kutaa kee filadhu",
    "education-level": "Sadarkaa Barnootaa",
    "select-education": "Sadarkaa barnootaa kee filadhu",
    elementary: "Mana Barnootaa Sadarkaa 1ffaa",
    middle: "Mana Barnootaa Sadarkaa Giddu Galeessaa",
    high: "Mana Barnootaa Sadarkaa 2ffaa",
    university: "Yuunivarsitii",
    next: "Itti Aanuu",
    back: "Duubatti",
    "create-avatar": "Avataara Kee Uumi",
    "choose-avatar-desc": "Avataara si bakka bu'u filadhu",
    "complete-setup": "Qophii Xumuri",

    // Navigation & Menu
    settings: "Qindaa'ina",
    profile: "Eenyummaa",
    language: "Afaan",
    quiz: "Gaaffiilee",
    multiplayer: "Taphachiisaa",
    leaderboard: "Sadarkaa",
    friends: "Hiriyoota",
    logout: "Ba'i",
    save: "Olkaa'i",
    cancel: "Dhiisi",
    "quick-play": "Taphaa Ariifataa",
    "1v1-battle": "Dorgommii 1 fi 1",
    "join-lobby": "Lobbii Seeni",
    "game-lobby": "Lobbii Taphaa",
    "avatar-store": "Suuqii Avataara",
    tournaments: "Dorgommiilee",
    mathematics: "Herrega",
    science: "Saayinsii",
    english: "Afaan Ingilizii",
    "general-knowledge": "Beekumsa Waliigalaa",
    "ai-tutor": "Barsiisaa AI",
    "learning-dna": "DNA Barnootaa",
    "social-feed": "Fiidii Hawaasaa",
    "academic-mode": "Haala Barnootaa",

    // Categories
    all: "Hunda",
    play: "Taphadi",
    learn: "Baradi",
    compete: "Dorgomi",
    social: "Hawaasa",

    // Descriptions
    "jump-into-quiz": "Gaaffii tasumaa seeni",
    "challenge-player": "Taphataa kakaasi",
    "find-matches": "Dorgommiilee barbaadi",
    "test-knowledge": "Beekumsa kee qoradhu",
    "compete-friends": "Hiriyoota waliin dorgomi",
    "join-matches-chat": "Dorgommiilee seenii fi mari",
    "see-whos-top": "Eenyu sadarkaa tokkoffaa akka ta'e ilaali",
    "customize-look": "Bifa kee miidhagssi",
    "global-competitions": "Dorgommiilee addunyaa",
    "numbers-algebra": "Lakkoofsa fi algebra",
    "physics-chemistry": "Fiiziiksii fi keemistrii",
    "grammar-vocabulary": "Seerluga fi jechoota",
    "history-geography": "Seenaa fi ji'oogiraafii",
    "24-7-ai-helper": "Gargaaraa AI sa'aa 24/7",
    "your-brain-map": "Kaartaa sammuu kee",
    "connect-chat": "Walitti hidhadhu fi mari",
    "posts-updates": "Barreeffamootaa fi haaromsa",
    preferences: "Filannoo",

    // Settings
    "customize-experience": "Muuxannoo kee miidhagssi",
    "avatar-editor": "Gulaalaa Avataara",
    general: "Waliigalaa",
    sound: "Sagalee",
    alerts: "Akeekkachiisota",
    privacy: "Iccitii",
    "choose-language": "Afaan filattu filadhu",
    active: "Hojjataa",
    "sound-settings": "Qindaa'ina Sagalee",
    "adjust-audio": "Filannoo sagalee sirreessi",
    "master-volume": "Sagalee Ijoo",
    mute: "Caljechi",
    max: "Ol'aanaa",
    "sound-effects": "Dhiibbaa Sagalee",
    "ui-sounds": "Sagalee UI fi dhiibbaa taphaa",
    vibration: "Sochoosa",
    "haptic-feedback": "Hojii irratti raafama",
    notifications: "Beeksisota",
    "manage-alerts": "Akeekkachiisota kee bulchi",
    "enable-all-notifications": "Beeksisota Hunda Dandeessisi",
    "master-switch": "Akeekkachiisota hundaaf ibsituu ijoo",
    "friend-requests": "Gaaffii Hiriyummaa",
    "when-someone-adds": "Namni tokko yoo si dabalate",
    messages: "Ergaawwan",
    "new-chat-messages": "Ergaa haasaa haaraa",
    "game-invites": "Affeerraa Taphaa",
    "multiplayer-invitations": "Affeerraa taphataa baay'ee",
    "daily-quiz-reminder": "Yaadachiisaa Gaaffii Guyyaa",
    "daily-challenge-notif": "Beeksisota qormaata guyyaa",
    achievements: "Galmawwan",
    "when-unlock-badges": "Baajota yoo bantu",
    "privacy-security": "Iccitii fi Nageenyummaa",
    "manage-privacy": "Iccitii kee bulchi",
    "public-profile": "Piroofaayilii Uummataa",
    "others-see-stats": "Namoonni biroo istaatiksii kee arguu danda'u",
    "show-online-status": "Haala Sarara Irraa Agarsiisi",
    "friends-see-online": "Hiriyoonni kee sarara irra jiraachuu kee haayuu",
    "activity-history": "Seenaa Sochii",
    "track-progress": "Guddina barnootaa kee hordofi",
    "account-actions": "Hojii Herregaa",
    "log-out": "Ba'i",
    "delete-account": "Herrega Haqi",
    "logged-out": "Milkiidhaan baatee jirta",

    // Enhanced Settings
    "profile-settings": "Qindaa'ina Piroofaayilii",
    "display-name": "Maqaa Mul'ataa",
    "your-display-name": "Maqaa mul'ataa kee",
    "email-address": "Teessoo Imeelii",
    "grade-level": "Sadarkaa Kutaa",
    "account-type": "Gosa Herregaa",
    "bio-optional": "Waa'ee Ofii (Filannoowwan)",
    "tell-about-yourself": "Waa'ee ofii kee himadhu...",
    "quick-actions": "Hojii Ariifataa",
    "save-profile": "Piroofaayilii Olkaa'i",
    "export-data": "Daataa Ergi",
    "push-notifications": "Beeksisota",
    "receive-quiz-reminders": "Yaadachiisaa gaaffilee fi haaromsa fudhadi",
    "play-sounds": "Yeroo gaaffilee sagalee taphachiisi",
    "mindforge-reactions": "MindForge Reactions™",
    "show-cinematic": "Deebii cinematic agarsiisi",
    "reduced-motion": "Haala Sochii Hir'ate",
    "limit-movement": "Sochii cimaa danda'amu daangeessi",
    "autosave-progress": "Ofumaan Olkaa'i",
    "auto-save-quiz": "Guddina gaaffilee ofumaan olkaa'i",
    "default-difficulty": "Sadarkaa Rakkina Durtii",
    easy: "Salphaa",
    medium: "Giddu galeessa",
    hard: "Cimaa",
    "privacy-display": "Iccitii fi Mul'ata",
    "show-avatar": "Avataara Agarsiisi",
    "display-avatar-others": "Avataara kee namoota biraaf agarsiisi",
    "show-rank": "Sadarkaa Agarsiisi",
    "display-rank-profile": "Sadarkaa kee piroofaayilii irratti agarsiisi",
    "allow-friend-requests": "Gaaffii Hiriyummaa Hayyami",
    "let-others-add": "Namoonni biroo gaaffii hiriyummaa akka siif ergatan hayyami",
    "saving-avatar": "Avataara olkaa'aa jira...",
    "profile-saved": "Piroofaayiliin milkiidhaan olkaa'ame!",
    "avatar-saved": "Avataarri milkiidhaan olkaa'ame!",
    "failed-save-profile": "Piroofaayilii olkaa'uun hin milkoofne",
    "failed-save-avatar": "Avataara olkaa'uun hin milkoofne",
    "data-exported": "Daataan milkiidhaan ergame!",
    "failed-export": "Daataa erguun hin milkoofne",
    "language-changed": "Afaan jijjiirame gara",
    "account-deletion-confirm": "Herrega haquuf mirkaneessuu barbaachisa. Gargaarsaaf deeggarsa argadhu.",

    // Quiz
    "daily-challenge": "Qormaata Guyyaa",
    "level-up": "Sadarkaa ol baate!",
    "correct-answer": "Sirrii!",
    "wrong-answer": "Dogoggora",
    "try-again": "Irra deebi'i yaali",
    "quiz-completed": "Gaaffileen xumuramaniiru",
    "start-quiz": "Gaaffii Jalqabi",
    difficulty: "Sadarkaa rakkina",
    questions: "Gaaffiilee",
    "browse-quizzes": "Gaaffiilee Ilaali",
    "quick-start": "Jalqabii Ariifataa",
    "select-subject": "Barnoota Filadhu",
    "select-difficulty": "Sadarkaa Rakkina Filadhu",
    "num-questions": "Baay'ina Gaaffilee",
    "generate-quiz": "Gaaffii Uumi",
    "no-quizzes": "Gaaffileen hin argamne",
    "correct-xp": "Sirrii! +15 XP badhaafame!",
    "incorrect-tomorrow": "Deebiin dogoggora. Boru irra deebi'ii yaali!",
    "question-of": "Gaaffii {current} {total} keessaa",
    score: "Qabxii",
    "time-left": "Yeroo Hafe",

    // Leaderboard
    "top-players": "Taphattoota Cimoo",
    "this-week": "Torban Kanaa",
    "this-month": "Ji'a Kanaa",
    "all-time": "Yeroo Hundaa",
    "your-rank": "Sadarkaa Kee",
    "active-players": "Taphattoota Hojjatoo",
    rank: "Sadarkaa",
    player: "Taphataa",
    level: "Sadarkaa",
    xp: "XP",

    // Social
    "social-hub": "Giddugala Hawaasaa",
    "connect-community": "Hawaasa kee waliin wal argadhu",
    feed: "Fiidii",
    groups: "Gareelee",

    // Multiplayer
    "create-room": "Kutaa Uumi",
    "join-room": "Kutaa Seeni",
    "room-name": "Maqaa Kutaa",
    "max-players": "Taphattoota Ol'aanaa",
    "waiting-players": "Taphattoota eegaa jira...",
    "game-starting": "Taphi jalqabaa jira...",
    ready: "Qophii",
    "not-ready": "Qophii Miti",

    // Common
    "get-started": "Jalqabi",
    "tap-to-continue": "Iddoo kamittuu tuqi itti fufuuf",
    theme: "Bifaaji'a",
    "dark-mode": "Bifa dukkana",
    "light-mode": "Bifa ifaa",
    music: "Muuziqaa",
    help: "Gargaarsa",
    terms: "Ulaagaalee",
    "privacy-policy": "Imaammata Iccitii",
    version: "Gulaala",
    "teacher-dashboard": "Dashboardii Barsiisaa",
    "admin-dashboard": "Dashboardii Bulchiinsaa",
    "create-quiz": "Gaaffilee Uumi",
    "my-quizzes": "Gaaffilee koo",
    "student-progress": "Fooya'ina Barataa",
    analytics: "Xiinxala",
    resources: "Meeshaalee Barnootaa",
    assignments: "Hojii Manaa",
    "flashcards": "Kaardii Ariifataa",
    "topic-coverage": "Uwwisa Mata Duree",
    "exam-mode": "Haala Qormaataa",
    "study-planner": "Karoora Qo'annoo",
    "academic-insights": "Hubannoo Barnootaa",

    // Footer
    "app-version": "Master Minds v1.0",
    "contact": "Qunnamtii",
  },
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>("english");
  
  const translate = (key: string): string => {
    return translations[language][key] || key;
  };
  
  return (
    <LanguageContext.Provider
      value={{
        language,
        setLanguage,
        t: translate,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
