import { Link } from "react-router-dom";
import { ArrowRight, BrainCircuit, Target } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { ErrorState, LoadingState } from "@/components/ui/status-state";
import type { LearningData } from "@/hooks/useLearningDNA";

interface LearningDNASummaryProps { data: LearningData | null; isLoading: boolean; error: Error | null; onRetry: () => void; }
const TopicList = ({ label, items, tone = "intelligence" }: { label: string; items: string[]; tone?: "intelligence" | "focus" }) => items.length ? <div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-muted-foreground">{label}</p><div className="mt-2 flex flex-wrap gap-1.5">{items.slice(0, 3).map((item) => <span key={item} className={tone === "focus" ? "rounded-full bg-warning/15 px-2.5 py-1 text-sm font-medium text-warning" : "rounded-full bg-upper-intelligence px-2.5 py-1 text-sm font-medium text-upper-intelligence-foreground"}>{item}</span>)}</div></div> : null;

export function LearningDNASummary({ data, isLoading, error, onRetry }: LearningDNASummaryProps) {
  if (isLoading) return <Card className="border-upper-intelligence/60"><LoadingState label="Loading your Learning DNA…" className="min-h-56" /></Card>;
  if (error) return <Card className="border-upper-intelligence/60"><ErrorState title="Learning DNA is unavailable" description="We couldn't load your academic learning map." actionLabel="Try again" onAction={onRetry} className="min-h-56" /></Card>;
  const hasData = Boolean(data && Object.keys(data.topicMastery).length > 0);
  if (!hasData) return <Card className="border-upper-intelligence/70 bg-card shadow-card"><CardContent className="flex min-h-56 flex-col items-start justify-center p-6 sm:p-8"><span className="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-upper-intelligence text-upper-intelligence-foreground"><BrainCircuit className="h-6 w-6" /></span><p className="text-xs font-semibold uppercase tracking-[0.14em] text-upper-intelligence-foreground">Learning DNA</p><h2 className="mt-2 text-xl font-semibold tracking-tight">Build your Learning DNA</h2><p className="mt-2 max-w-xl text-sm leading-6 text-muted-foreground">Understand your strengths and find what to focus on next.</p><Button asChild className="mt-5 min-h-11"><Link to="/learning-dna">Build Learning DNA <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></CardContent></Card>;
  const recommendation = data!.predictedPath?.recommendedFocus[0] || data!.weaknesses[0];
  return <Card className="overflow-hidden border-upper-intelligence/70 bg-card shadow-card"><CardContent className="p-0"><div className="border-b border-upper-intelligence/60 bg-upper-intelligence px-6 py-5 sm:px-8"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2 text-upper-intelligence-foreground"><BrainCircuit className="h-5 w-5" /><p className="text-sm font-semibold">Learning DNA</p></div><h2 className="mt-2 text-xl font-semibold tracking-tight">Your academic learning map</h2><p className="mt-1 text-sm text-muted-foreground">Turn your current analysis into a focused study plan.</p></div><Link to="/learning-dna" aria-label="Open Learning DNA" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-card text-upper-intelligence-foreground shadow-sm transition-colors hover:bg-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring"><ArrowRight className="h-5 w-5" /></Link></div></div><div className="grid gap-5 px-6 py-5 sm:grid-cols-3 sm:px-8"><TopicList label="Strengths" items={data!.strengths} /><TopicList label="Focus next" items={data!.weaknesses} tone="focus" /><TopicList label="Recommended" items={data!.predictedPath?.recommendedFocus || []} /></div>{recommendation ? <div className="mx-6 mb-6 flex flex-col gap-3 rounded-xl border border-primary/20 bg-primary/5 p-4 sm:mx-8 sm:flex-row sm:items-center sm:justify-between"><div className="flex items-center gap-3"><span className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary text-primary-foreground"><Target className="h-5 w-5" /></span><div><p className="text-xs font-semibold uppercase tracking-[0.12em] text-primary">Your next step</p><p className="font-semibold">Review {recommendation}</p></div></div><Button asChild className="min-h-11"><Link to="/revision">Study now <ArrowRight className="ml-2 h-4 w-4" /></Link></Button></div> : <div className="mx-6 mb-6 flex items-center gap-2 rounded-xl bg-muted p-3 text-sm text-muted-foreground sm:mx-8"><Target className="h-4 w-4 text-primary" /> Your analysis is ready; open Learning DNA to review your academic map.</div>}</CardContent></Card>;
}
